### ISSUE TITLE
General Usage Question #2

### ISSUE THREAD

**Issue by SLinAppliedBiomath** [garyd203/xraysink#37]
Following on
https://github.com/garyd203/xraysink/issues/22

I noticed the use of AsyncContext for FastApi, is this using the xraysink or aws sdk? Is it needed?

I've attempted an implementation with either and have found that my async request handlers are unable to retrieve the context. This leads to AttributeErrors or just general errors where the segment cannot be found

**Comment by garyd203** [comment]
Hi @SLinAppliedBiomath , sorry it sometimes takes a few days before I can respond. The custom `AsyncContext` in `xraysink` is intended to address an instrumentation bug with running tasks (that is, a standard Python asyncio task or future) - it won't do anything for your request handlers. So you shouldn't need it if you are only instrumenting a FastAPI service.

**Comment by garyd203** [comment]
PS: I notice you closed this ticket - have you solved your problem?

**Comment by SLinAppliedBiomath** [comment]
Hi Gary! Thanks for the help. I was able to resolve my problem but still have some question.
When testing for FastAPI without using the AsyncContext did you notice rapid firing request would start/end segments from other requests?

**Comment by garyd203** [comment]
Hi, that does sound a lot like the problem I encountered.

In my case I was using a plugin (`tartiflette`) that often creates an asyncio task for making downstream requests. I hadn't seen that happen in vanilla FastAPI implementation though - I thought each request was handled inline, but perhaps I am wrong.

It is true that the `AsyncContext` that comes with `aws_xray_sdk` will be broken if you use asyncio tasks, in the way that you describe (FYI, it incorrectly shares the "current segment" stack amongst all asyncio tasks started from a common entry point, and then unwinds that stack in an arbitrarily wrong order as each segment/HTTP request finishes).

Anyway, you are welcome to use `xraysink`'s `AsyncContext` all the time. The only reason I don't recommend that in general is because i thought it wasn't necessary and I was trying to take a light touch, but I might update the doco based on what you are saying.

thanks,
  gary

**Comment by SLinAppliedBiomath** [comment]
That's very interesting, I'm running FastAPI through uvicorn (rather new to either technology, but that sounds pretty vanilla). 
I found that I couldn't resolve the "race-condition" issue unless I was using AsynContext, which presented another issue. When configuring xray_recorder, AsyncContext was initialized with an event_loop that was later replaced by uvicorn with uvloop, which made it impossible to find any segments.

**Comment by garyd203** [comment]
Hmm, I tend to use `gunicorn` + `uvicorn` + `fastapi`, but with the builtin Python asyncio loop, rather than uvloop. Hence I don't have much experience with other loops - although I have certainly lost plenty of hair due to a process ending up with multiple loops!

I think if you don't provide any context to `xray_recorder.configure` then it uses a default non-async context, which may explain why initially you had the race condition bug, but the uvloop replacement didn't cause errors.

There's an option to pass the loop in to `AsyncContext` as a constructor argument. What happens if you wait until uvicorn has set up it's uvloop, and then do `xray_recorder.configure` passing in uvicorn's `uvloop` as the `loop` parameter when you create `AsyncContext`? (NB: Avoid calling `xray_recorder.configure` twice in your process setup, that seems to cause other issues because `configure` isn't as idempotent as it seems to be)

**Comment by SLinAppliedBiomath** [comment]
That's what I ended up doing (which is why i closed the issue). Now i'm more curious how you were able to avoid the issue in general with vanilla fastapi

**Comment by garyd203** [comment]
Yeah, I'm not sure why I don't have the problem with the event loop being replaced. My best guess is that this might be because you are using `uvloop` instead of the builtin `asyncio` loop, and `aws_xray_sdk` goes looking for the default builtin loop if you don't supply one explicitly.

Anyway, glad that you have your setup working now. Good luck with it!
