### ISSUE TITLE
Question AWS- Background TASK

### ISSUE THREAD

**Issue by Arwiim** [garyd203/xraysink#93]
My question is, how can I make xray trace my calls to the database, this would be a background task. Currently you can see that the task is running but it does not give me information about the host and also the task is repeated, what is this due to?

AWS-RAY conf
![image](https://user-images.githubusercontent.com/53288078/204847738-bf326096-748f-42f3-a249-f418ec8fa396.png)

This is aws-trace
![image](https://user-images.githubusercontent.com/53288078/204847441-ec97a4fe-0ee4-4177-a4ed-650e10d4de5b.png)

This is my async task
![image](https://user-images.githubusercontent.com/53288078/204846282-bfe67b3c-dda9-4cb5-9929-491387066c27.png)

**Comment by garyd203** [comment]
Hi @Arwiim , thanks for providing code snippets, that's really helpful. AIUI you want to trace FASTAPi request handling through to your database.

Firstly, it looks like you've got the middleware configuration with `xraysink` right, so well done.

However, you shouldn't have the `@xray_task_async` decorator on your request handler function - that function will already be traced by the middleware. `@xray_task_async` is instead intended for background functions that don't come from a request (and hence won't be automatically instrumented by the middleware).

To your question, I suspect that the reason why you're not seeing database calls in the X-Ray trace is because your database library is not directly supported by X-Ray. Database libraries are instrumented by the main `aws_xray_sdk` library - see [their documentation](https://github.com/aws/aws-xray-sdk-python#trace-sql-queries).

It's a bit confusing using two libraries together, so here's a break down of which library does what:
* Add tracing to HTTP requests handled by FastAPI (or another async Python web framework): `xraysink` (via [middleware](https://github.com/garyd203/xraysink#fastapi))
* Add tracing to background (non-HTTP-request) functions written as async Python functions: `xraysink` (via [xray_task_async](https://github.com/garyd203/xraysink#background-jobstasks) decorator)
* everything else: [aws_xray_sdk](https://github.com/aws/aws-xray-sdk-python)

HTH

**Comment by Arwiim** [comment]
Tanks! this was very helpful :D
